# Form implementation generated from reading ui file '.\dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DashBoard(object):
    def setupUi(self, DashBoard):
        DashBoard.setObjectName("DashBoard")
        DashBoard.setEnabled(True)
        DashBoard.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DashBoard.sizePolicy().hasHeightForWidth())
        DashBoard.setSizePolicy(sizePolicy)
        DashBoard.setWindowOpacity(1.0)
        DashBoard.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        DashBoard.setStyleSheet("background-color: rgb(50, 50, 50)")
        DashBoard.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=DashBoard)
        self.centralwidget.setObjectName("centralwidget")
        self.label_blinker_left = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_blinker_left.setGeometry(QtCore.QRect(170, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_blinker_left.setFont(font)
        self.label_blinker_left.setStyleSheet("color: white")
        self.label_blinker_left.setText("")
        self.label_blinker_left.setPixmap(QtGui.QPixmap(":/resources/resources/left_arrow_off.png"))
        self.label_blinker_left.setWordWrap(False)
        self.label_blinker_left.setObjectName("label_blinker_left")
        self.label_gear = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_gear.setGeometry(QtCore.QRect(230, 30, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_gear.setFont(font)
        self.label_gear.setStyleSheet("background-color: rgba(0, 0, 0, 0%);\n"
"color: white;")
        self.label_gear.setText("None")
        self.label_gear.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_gear.setWordWrap(False)
        self.label_gear.setObjectName("label_gear")
        self.label_speedometer_digits = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_speedometer_digits.setGeometry(QtCore.QRect(190, 80, 261, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_speedometer_digits.setFont(font)
        self.label_speedometer_digits.setAutoFillBackground(False)
        self.label_speedometer_digits.setStyleSheet("background-color: rgba(0, 0, 0, 0%);\n"
"color: white;")
        self.label_speedometer_digits.setText("None")
        self.label_speedometer_digits.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_speedometer_digits.setWordWrap(False)
        self.label_speedometer_digits.setObjectName("label_speedometer_digits")
        self.label_blinker_right = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_blinker_right.setGeometry(QtCore.QRect(420, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_blinker_right.setFont(font)
        self.label_blinker_right.setStyleSheet("color: white")
        self.label_blinker_right.setText("")
        self.label_blinker_right.setPixmap(QtGui.QPixmap(".\\resources/right_arrow_off.png"))
        self.label_blinker_right.setWordWrap(False)
        self.label_blinker_right.setObjectName("label_blinker_right")
        self.label_speedometer_analog = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_speedometer_analog.setGeometry(QtCore.QRect(0, 160, 640, 411))
        self.label_speedometer_analog.setText("")
        self.label_speedometer_analog.setPixmap(QtGui.QPixmap(":/resources/resources/speedometer.png"))
        self.label_speedometer_analog.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_speedometer_analog.setObjectName("label_speedometer_analog")
        self.label_speedometer_analog.raise_()
        self.label_blinker_left.raise_()
        self.label_gear.raise_()
        self.label_speedometer_digits.raise_()
        self.label_blinker_right.raise_()
        DashBoard.setCentralWidget(self.centralwidget)

        self.retranslateUi(DashBoard)
        QtCore.QMetaObject.connectSlotsByName(DashBoard)

    def retranslateUi(self, DashBoard):
        _translate = QtCore.QCoreApplication.translate
        DashBoard.setWindowTitle(_translate("DashBoard", "Dashboard"))
