# Form implementation generated from reading ui file '.\dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DashBoard(object):
    def setupUi(self, DashBoard):
        DashBoard.setObjectName("DashBoard")
        DashBoard.setEnabled(True)
        DashBoard.resize(1024, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DashBoard.sizePolicy().hasHeightForWidth())
        DashBoard.setSizePolicy(sizePolicy)
        DashBoard.setWindowOpacity(1.0)
        DashBoard.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        DashBoard.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(parent=DashBoard)
        self.centralwidget.setObjectName("centralwidget")
        self.label_blinker_left = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_blinker_left.setGeometry(QtCore.QRect(300, 50, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_blinker_left.setFont(font)
        self.label_blinker_left.setText("None")
        self.label_blinker_left.setWordWrap(False)
        self.label_blinker_left.setObjectName("label_blinker_left")
        self.label_blinker_right = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_blinker_right.setGeometry(QtCore.QRect(600, 50, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_blinker_right.setFont(font)
        self.label_blinker_right.setText("None")
        self.label_blinker_right.setWordWrap(False)
        self.label_blinker_right.setObjectName("label_blinker_right")
        self.label_gear = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_gear.setGeometry(QtCore.QRect(440, 320, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label_gear.setFont(font)
        self.label_gear.setText("None")
        self.label_gear.setWordWrap(False)
        self.label_gear.setObjectName("label_gear")
        self.lcd_speedometer = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.lcd_speedometer.setGeometry(QtCore.QRect(370, 210, 261, 71))
        self.lcd_speedometer.setDigitCount(8)
        self.lcd_speedometer.setProperty("value", 123.0)
        self.lcd_speedometer.setObjectName("lcd_speedometer")
        DashBoard.setCentralWidget(self.centralwidget)

        self.retranslateUi(DashBoard)
        QtCore.QMetaObject.connectSlotsByName(DashBoard)

    def retranslateUi(self, DashBoard):
        _translate = QtCore.QCoreApplication.translate
        DashBoard.setWindowTitle(_translate("DashBoard", "Dashboard"))
